# Generated by Django 5.0.7 on 2025-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("portfolio_value", models.FloatField()),
                ("nifty_50", models.FloatField()),
                ("gold", models.FloatField()),
                ("portfolio_return", models.FloatField()),
                ("nifty_50_return", models.FloatField()),
                ("gold_return", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Holdings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("avg_price", models.FloatField()),
                ("current_price", models.FloatField()),
                ("sector", models.CharField(max_length=50)),
                ("market_cap", models.CharField(max_length=50)),
                ("exchange", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("gain_loss", models.FloatField()),
                ("gain_loss_percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MarketCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_cap", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("percentage", models.FloatField()),
                ("holdings_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SectorAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("percentage", models.FloatField()),
                ("holdings_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=50)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TopPerformers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("performance", models.FloatField()),
            ],
        ),
    ]
