# Generated by Django 5.0.7 on 2025-08-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalPerformance",
            new_name="Historical_Performance",
        ),
        migrations.RenameModel(
            old_name="MarketCap",
            new_name="Market_Cap",
        ),
        migrations.RenameModel(
            old_name="SectorAllocation",
            new_name="Sector_Allocation",
        ),
        migrations.RenameModel(
            old_name="TopPerformers",
            new_name="Top_Performers",
        ),
    ]
