# Generated by Django 5.0.7 on 2025-08-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_rename_date_historical_performance_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="Value",
            field=models.CharField(max_length=50),
        ),
    ]
