# Generated by Django 5.0.7 on 2025-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_summary_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market_cap",
            name="Value",
            field=models.CharField(max_length=50),
        ),
    ]
